### ISSUE TITLE
Upgrade nuxt to rc*

### ISSUE THREAD

**Issue by pi0** [piyushchauhan2011/nuxt-with-jest#2]
Hi. When i was reading tests it seems that requires are still using `alpha` convention and [here](https://github.com/piyushchauhan2011/nuxt-with-jest/blob/master/yarn.lock#L3367) yarn.lock is still with alpha.5. I think it would be better require nuxt `1.0.0-rc3` instead of `latest`. Also programmatic usage has been changed since rc releases. Please refer to nuxt internal tests like [this](https://github.com/nuxt/nuxt.js/blob/dev/test/basic.dev.test.js#L17) or [WIP docs](https://github.com/nuxt/docs/blob/1.0/en/api/nuxt.md) for upgrading usage.

**Comment by husayt** [comment]
@piyushchauhan2011 would be great to  update this to use latest nuxt (1.3.0 is the latest) and it will be great to add this  to nuxt  examples:
https://github.com/nuxt/nuxt.js/edit/dev/examples

it will be useful to many others

**Comment by ausir0726** [comment]
I upgrade to nuxt 1.4.1 and fix this repo for jest test .

https://github.com/piyushchauhan2011/nuxt-with-jest/pull/3
